In [57]:
import pandas as pd

In [58]:
# csv_path = "data.csv"
# df = pd.read_csv(csv_path)
# df.head()

In [59]:
# xslx_path = "data.xlsx"
# df - pd.read_excel(xslx_path)
# df.head()

In [60]:
songs = {'Album': ["Thriller", "Back in Black" , "The Dark Side of the Moon" ,'The Bodyguard' , 'Bat Out of Hell'] , 
        'Released':[1982 , 1980,1973,1882 , 1977],
         'Length':['00:42:19' , '00:42:11' , '00:42:49' , '00:57:44' ,  '00:46:33']
        }
df = pd.DataFrame(songs)
df.head()

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1              Back in Black      1980  00:42:11
2  The Dark Side of the Moon      1973  00:42:49
3              The Bodyguard      1882  00:57:44
4            Bat Out of Hell      1977  00:46:33

In [61]:
x = df[['Length' , 'Album']]
x.head()

     Length                      Album
0  00:42:19                   Thriller
1  00:42:11              Back in Black
2  00:42:49  The Dark Side of the Moon
3  00:57:44              The Bodyguard
4  00:46:33            Bat Out of Hell

In [62]:
print(df.iloc[0,0])

Thriller

In [63]:
print(df.loc[0 , 'Released'])

1982

In [64]:
print(df.at[2 , 'Released'])

1973

In [65]:
y = df.iloc[0:3 ,0:3]
y

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1              Back in Black      1980  00:42:11
2  The Dark Side of the Moon      1973  00:42:49

In [66]:
z = df.loc[0:2 , 'Album':'Length']
z

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1              Back in Black      1980  00:42:11
2  The Dark Side of the Moon      1973  00:42:49

In [67]:
print(df['Released'].unique())

[1982 1980 1973 1882 1977]

In [68]:
df1 = df[df['Released']>=1980]

In [69]:
df1

           Album  Released    Length
0       Thriller      1982  00:42:19
1  Back in Black      1980  00:42:11

In [70]:
df1.to_csv("new_songs.csv")

In [71]:
df2=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

In [72]:
df2['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [73]:

# %pip install xlrd openpyxl

In [74]:
!pip install xlrd openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlrd in c:\users\marse\appdata\roaming\python\python313\site-packages (2.0.2)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [75]:
# import pandas as pd
# from pyodide.http import pyfetch

In [76]:
# filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"

# async def download(url , filename):
#     response = await pyfetch(url)
#     if response.status == "200":
#         with open(filename , "wb") as f:
#             f.write(await response.bytes())

# await sownload(filename , "Product-sales.csv")
# df = pd.read_csv("Product-sales.csv")

In [77]:
# Print first five rows of the dataframe

# df.head()

In [78]:
# Read data from Excel File and print the first five rows

# xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'

# await download(xlsx_path, "Product-sales.xlsx")
# df = pd.read_excel("Product-sales.xlsx")
# df.head()

In [81]:
#We can access the column Quantity and assign it a new dataframe x:
x = df[['Album']]
x

                       Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon
3              The Bodyguard
4            Bat Out of Hell

In [80]:
# Get the column as a series

x = df['Album']
x

0                     Thriller
1                Back in Black
2    The Dark Side of the Moon
3                The Bodyguard
4              Bat Out of Hell
Name: Album, dtype: object